### ISSUE TITLE
Split the budget for May content

### ISSUE THREAD

**Issue by viniblack** [w3b3d3v/content-team#12]
We have 2k dol for the May content, so we need to think about how to divide it up for each task.

**Comment by viniblack** [comment]
[The card has more detailed planning](https://github.com/orgs/w3b3d3v/projects/13/views/1?pane=issue&itemId=59857919)

[Link to spreadsheet](https://docs.google.com/spreadsheets/d/1EWI1WV1myy4j7Sc6Qw9wcMbIJH_FunYnXq5qMkUAqp0/edit?usp=sharing)


![Image](https://github.com/w3b3d3v/content-team/assets/51183682/c7b6a583-ac0e-4a23-97af-d3735d39ee91)

**Comment by allluz** [comment]
the rest of the amount will be distributed to bounties, paid traffic and partnerships with influencers. during the first month, we only tested the creators' publications
