### ISSUE TITLE
Playlist Rust

### ISSUE THREAD

**Issue by allluz** [w3b3d3v/content-team#13]
We've recorded some rust exercises, we're going to edit them and upload them to our YouTube channel.

* [Playlist no loom](https://www.loom.com/spaces/WEB3DEV-27965514/folders/rust-state-machine-10961a96273c4f068de9de99249da2c0)
* [Rust study group script](https://github.com/w3b3d3v/rust-grupo-estudo)
* [Project repository](https://github.com/w3b3d3v/rust-state-machine)
* [Rust community on twitter](https://twitter.com/i/communities/1782470648226283818)

**Comment by viniblack** [comment]
We'll start posting these videos by Wednesday
