### ISSUE TITLE
Edition`s setting

### ISSUE THREAD

**Issue by allluz** [w3b3d3v/content-team#17]
- [x] Pop-us throughout the video with personalized WEB3DEV`s accounts stickers; 
- [x] Put a preview at the end of the videos suggesting the next video to watch (that correlates with the content)
- [x] Invitation from the creators to comment on keywords. Editor will include the highlighted word in the edition.

**Comment by viniblack** [comment]
@allluz add the link to these assets here please

**Comment by allluz** [comment]
Assistiu até o final? Comente #DAOS
